---
- name: Install and configure Nginx on web servers
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Change default Nginx port to 8081
      lineinfile:
        path: /etc/nginx/sites-available/default
        regexp: '^\s*listen\s+80'
        line: "        listen {{ http_port }};"
        backrefs: yes
      notify: Restart Nginx

    - name: Set start page with hostname
      copy:
        dest: /var/www/html/index.html
        content: "Hostname: {{ inventory_hostname }}!"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
